name: DLH
on:
  push:
    branches:
      - feat/*
jobs:
  call_reusable:
    uses: ./.github/workflows/ex4.yaml
    with:
      node_version: '20'

  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v5
      - id: foo
        uses: elkanuco/hello-world-composite-action@feat/myfeature_5
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
