name: interact with Github API
on: 
  pull_request:

jobs:
  create-issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate short SHA
        id: short_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create issue via GitHub API
        env:
          SHORT_SHA: ${{ steps.short_sha.outputs.sha_short }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl --request POST --url https://api.github.com/repos/elkanuco/dlh_devops/issues \
          --header "authorization: Bearer $GITHUB_TOKEN" \
          --header "content-type: application/json" \
          --data "{\"title\": \"Automated issue for commit: $SHORT_SHA\",\"body\": \"This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**.\n\nThe commit hash was: _$SHORT_SHA_.\"}"
