name: Switch Node version
on: 
  pull_request:

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4
        - name : setup node
          uses: actions/setup-node@v4
          with:
            node-version:  ${{env.NODE_VERSION}}
        - name: run test
          shell: bash
          run: |
            npm install
            npm test
        - name: check version
          shell: bash
          run: node -v
